In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('file:///E:/Windows%20Malware/Iris.csv')

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
# This line extracts the first four columns of the DataFrame df as features (X). 
# It uses the iloc indexer to select all rows (:) and the first four columns (:4). 
# The .values attribute converts the selected DataFrame subset into a NumPy array.
X=df.iloc[:,:4].values

y = df['Species'].values

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [13]:
y_pred = classifier.predict(X_test)
y_pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor'], dtype='<U15')

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(y_test, y_pred))
print(cm)

Accuracy :  1.0
[[14  0  0]
 [ 0  7  0]
 [ 0  0  9]]


In [15]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
print(df)

        Real Values Predicted Values
0       Iris-setosa      Iris-setosa
1    Iris-virginica   Iris-virginica
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4       Iris-setosa      Iris-setosa
5   Iris-versicolor  Iris-versicolor
6       Iris-setosa      Iris-setosa
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9       Iris-setosa      Iris-setosa
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12   Iris-virginica   Iris-virginica
13   Iris-virginica   Iris-virginica
14   Iris-virginica   Iris-virginica
15   Iris-virginica   Iris-virginica
16  Iris-versicolor  Iris-versicolor
17   Iris-virginica   Iris-virginica
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20      Iris-setosa      Iris-setosa
21      Iris-setosa      Iris-setosa
22  Iris-versicolor  Iris-versicolor
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25      Iris-setosa      Iris-setosa
2

In [16]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

In [17]:
m=accuracy_score(y_test, y_pred)
print("error rate:-",1-m)

error rate:- 0.0


In [18]:
# Calculate precision score
precision = precision_score(y_test, y_pred, average='weighted')

# Calculate recall score
recall = recall_score(y_test, y_pred, average='weighted')

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)

# Print the scores
print("Precision:", precision)
print("Recall:", recall)
print("Accuracy:", accuracy)

Precision: 1.0
Recall: 1.0
Accuracy: 1.0
